services:
  xui-aggregator:
    build: .
    container_name: xui_aggregator
    restart: always
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8001"]
